---
title: "My Data Visualisation Project"
author: "Seline Uran"
output: html_document
---
```{r = diagram1, echo=FALSE, message=FALSE}
#To begin load the following libraries in RStudio for all future tasks

library(ggplot2)
library(readxl)
library(RColorBrewer)
library(scales)
library(dplyr)
library(tidyr)
library(tidyverse)
```

<span style="text-decoration:underline">Data Origins</span>

<span style="text-decoration:underline">Research Questions</span>

<span style="text-decoration:underline">Data Preparation</span>


<span style="text-decoration:underline">Main Diagram</span>
 

For the main visualisation I performed the following steps before visualising 
the data. 



<span style="text-decoration:underline">Visualisation</span>

```{r = maindiagram, echo=FALSE, message=FALSE, results='hide'}
rawdata <- read_excel("~/myfinalproject/processed/rs_statistics.xlsx")

rs2<- rawdata %>% slice(1:11)

rs2$`Local authority ONS code`<-NULL
rs2$`Local authority`<-NULL
rs2$`Region ONS code`<- NULL

rs2<- rs2[-c(1:3), ]

rs2_long <- rs2 %>% 
  gather(Year, Number, -Region)
rs2_long

rs2plot <-ggplot(rs2_long, aes(x = Year, y = Number, color = Region, group = Region)) +
  geom_point() +
  geom_line() +
  scale_color_brewer(palette = 'Dark2') +
  theme_classic(base_size = 12)

rs2plot

ggsave("figures/rs2plot.png")

```



```{r = diagram2, echo=FALSE, message=FALSE, results='hide'}
rawdata <- read_excel("~/myfinalproject/processed/rs_statistics.xlsx")

rs1<- rawdata %>% slice(1:2)

rs1$`Local authority ONS code`<-NULL
rs1$`Region ONS code`<-NULL
rs1$`Local authority`<-NULL

rs1_long <- rs1 %>% 
  gather(Year, Number, -Region)
rs1_long

rs1plot <- ggplot(rs1_long, aes(x = Year, y = Number, color = Region, group = Region)) +
  geom_point() +
  geom_line() +
  scale_color_brewer(palette = 'Dark2') +
  theme_classic(base_size = 12)

rs1plot
ggsave("figures/rs1plot.png")

``` 


```{r = diagram3, echo=FALSE, message=FALSE, results='hide'}

data4 <- read_excel("~/myfinalproject/processed/data4.xlsx")

d4 <- data.frame(
  Group = c("Leeds", "Sheffield", "Kingston upon Hull, City of", "Doncaster", 
            "East Riding of Yorkshire", "Scarborough", "Barnsley"),
  value = c(35, 24, 19, 13, 11, 11, 10)
  )

bp<- ggplot(d4, aes(x="", y=value, fill=Group))+
  geom_bar(width = 1, stat = "identity")

pie <- bp + coord_polar("y", start=0)

blank_theme <- theme_minimal()+
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid=element_blank(),
    plot.title=element_text(size=14, face="bold")
  )

pie<- pie + scale_fill_brewer(palette="Dark2") + blank_theme +
  theme(axis.text.x=element_blank())+
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=0)

pie
```



<span style="text-decoration:underline">Summary</span>


<span style="text-decoration:underline">Future Directions</span>


